In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import scipy.stats as stats
from google.colab import files

In [21]:
# Dictionary of promoted teams per season
promoted_teams = {
    '2014-2015': ['Leicester City', 'QPR', 'Burnley'],
    '2015-2016': ['Norwich City', 'Bournemouth', 'Watford'],
    '2016-2017': ['Hull City', 'Burnley', 'Middlesbrough'],
    '2017-2018': ['Brighton', 'Newcastle United', 'Huddersfield'],
    '2018-2019': ['Fulham', 'Wolves', 'Cardiff City'],
    '2019-2020': ['Norwich City', 'Aston Villa', 'Sheffield United'],
    '2020-2021': ['Fulham', 'West Brom', 'Leeds United'],
    '2021-2022': ['Brentford', 'Watford', 'Norwich City'],
    '2022-2023': ['Fulham', 'Bournemouth', 'Nottingham Forest'],
    '2023-2024': ['Burnley', 'Sheffield United', 'Luton Town']
}

In [22]:
premier_ranking_modified = pd.read_excel("/content/Premier_League_Data_Combined_Modified.xlsx")
premier_market_value = pd.read_excel("/content/Premier_Market_Value.xlsx")
premier_goal_keeping = pd.read_excel("/content/Premier_League_Goal_Keeping.xlsx")

In [23]:
premier_ranking_modified

,Season,Date,Home,Score,Away,Game Outcome,Outcome_Label,LSPR,LSGFD,LSGAD,LSYCD,LSPD,R5PD,R5GFD,R5GAD
0,2023-2024,2023-08-11,Burnley,0–3,Manchester City,Loss,0,0.653272,-50.666667,31.0,33.333333,-6.333333,-6,-0.4,1.0
1,2023-2024,2023-08-12,Arsenal,2–1,Nottingham Forest,Win,2,1.577128,50.000000,-25.0,-33.000000,0.000000,1,0.2,-0.6
2,2023-2024,2023-08-12,Everton,0–1,Fulham,Loss,0,0.877049,-21.000000,4.0,1.000000,-2.000000,1,-0.2,-0.2
3,2023-2024,2023-08-12,Sheffield United,0–1,Crystal Palace,Loss,0,0.912887,3.333333,15.0,-4.666667,1.666667,-2,-1.4,0.0
4,2023-2024,2023-08-12,Brighton,4–1,Luton Town,Win,2,1.424290,28.666667,-11.0,-19.333333,3.333333,7,1.8,1.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,2013-2014,2014-05-11,Cardiff City,1–2,Chelsea,Loss,0,NaN,0.000000,0.0,0.000000,0.000000,-6,-1.0,1.8
4176,2013-2014,2014-05-11,West Brom,1–2,Stoke City,Loss,0,NaN,0.000000,0.0,0.000000,0.000000,-3,-0.2,0.6
4177,2013-2014,2014-05-11,Tottenham,3–0,Aston Villa,Win,2,NaN,0.000000,0.0,0.000000,0.000000,6,1.6,-0.6
4178,2013-2014,2014-05-11,Norwich City,0–2,Arsenal,Loss,0,NaN,0.000000,0.0,0.000000,0.000000,-11,-1.6,1.0
4179,2013-2014,2014-05-11,Sunderland,1–3,Swansea City,Loss,0,NaN,0.000000,0.0,0.000000,0.000000,7,1.0,-0.4

In [24]:
premier_market_value

,Team,Squad,Age,Foreigners,Average Market Value,Total Market Value,Season
0,Chelsea,31,24.4,24,10690000.0,331480000.0,2004-2005
1,Manchester United,37,24.2,25,7930000.0,293230000.0,2004-2005
2,Arsenal,37,23.4,29,6680000.0,247000000.0,2004-2005
3,Liverpool,38,24.8,26,5850000.0,222130000.0,2004-2005
4,Tottenham,37,24.6,21,3440000.0,127250000.0,2004-2005
...,...,...,...,...,...,...,...
395,Fulham,26,27.6,23,13320000.0,346300000.0,2023-2024
396,Everton,24,27.6,11,13810000.0,331400000.0,2023-2024
397,Burnley,34,25.2,26,7570000.0,257430000.0,2023-2024
398,Sheffield United,29,25.8,17,4210000.0,122000000.0,2023-2024
399,Luton Town,36,26.9,20,3210000.0,115650000.0,2023-2024

In [25]:
# Merge premier_market_value into premier_ranking_modified
premier_ranking_modified = pd.merge(premier_ranking_modified, premier_market_value,  how='left', left_on=['Home','Season'], right_on=['Team','Season'])
premier_ranking_modified = premier_ranking_modified.rename(columns={
    'Squad': 'HomeSquad',
    'Age': 'HomeAge',
    'Foreigners': 'HomeForeigners',
    'Total Market Value': 'HomeTotalMarketValue'
})

premier_ranking_modified = pd.merge(premier_ranking_modified, premier_market_value,  how='left', left_on=['Away','Season'], right_on=['Team','Season'])
premier_ranking_modified = premier_ranking_modified.rename(columns={
    'Squad': 'AwaySquad',
    'Age': 'AwayAge',
    'Foreigners': 'AwayForeigners',
    'Total Market Value': 'AwayTotalMarketValue'
})

premier_ranking_modified

,Season,Date,Home,Score,Away,Game Outcome,Outcome_Label,LSPR,LSGFD,LSGAD,...,HomeAge,HomeForeigners,Average Market Value_x,HomeTotalMarketValue,Team_y,AwaySquad,AwayAge,AwayForeigners,Average Market Value_y,AwayTotalMarketValue
0,2023-2024,2023-08-11,Burnley,0–3,Manchester City,Loss,0,0.653272,-50.666667,31.0,...,25.2,26,7570000.0,2.574300e+08,Manchester City,26,26.2,17,50820000.0,1.320000e+09
1,2023-2024,2023-08-12,Arsenal,2–1,Nottingham Forest,Win,2,1.577128,50.000000,-25.0,...,25.6,19,42940000.0,1.160000e+09,Nottingham Forest,33,26.6,26,11730000.0,3.872500e+08
2,2023-2024,2023-08-12,Everton,0–1,Fulham,Loss,0,0.877049,-21.000000,4.0,...,27.6,11,13810000.0,3.314000e+08,Fulham,26,27.6,23,13320000.0,3.463000e+08
3,2023-2024,2023-08-12,Sheffield United,0–1,Crystal Palace,Loss,0,0.912887,3.333333,15.0,...,25.8,17,4210000.0,1.220000e+08,Crystal Palace,28,26.5,13,15780000.0,4.417000e+08
4,2023-2024,2023-08-12,Brighton,4–1,Luton Town,Win,2,1.424290,28.666667,-11.0,...,24.6,25,14620000.0,5.117500e+08,Luton Town,36,26.9,20,3210000.0,1.156500e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,2013-2014,2014-05-11,Cardiff City,1–2,Chelsea,Loss,0,NaN,0.000000,0.0,...,25.4,26,2090000.0,8.790000e+07,Chelsea,49,24.7,40,11920000.0,5.842000e+08
4176,2013-2014,2014-05-11,West Brom,1–2,Stoke City,Loss,0,NaN,0.000000,0.0,...,27.2,24,2750000.0,9.080000e+07,Stoke City,33,26.5,23,3170000.0,1.047000e+08
4177,2013-2014,2014-05-11,Tottenham,3–0,Aston Villa,Win,2,NaN,0.000000,0.0,...,23.8,22,7050000.0,2.889500e+08,Aston Villa,36,24.7,22,3040000.0,1.095000e+08
4178,2013-2014,2014-05-11,Norwich City,0–2,Arsenal,Loss,0,NaN,0.000000,0.0,...,26.6,18,2790000.0,8.930000e+07,Arsenal,41,24.5,34,9410000.0,3.857500e+08
4179,2013-2014,2014-05-11,Sunderland,1–3,Swansea City,Loss,0,NaN,0.000000,0.0,...,25.6,28,3130000.0,1.220000e+08,Swansea City,36,25.7,28,3580000.0,1.289300e+08

In [26]:
# Drop the Average Market Value_x Average Market Value_y, Team_x, Team_y columns
premier_ranking_modified = premier_ranking_modified.drop(columns=['Average Market Value_x', 'Average Market Value_y', 'Team_x', 'Team_y'])

premier_ranking_modified

,Season,Date,Home,Score,Away,Game Outcome,Outcome_Label,LSPR,LSGFD,LSGAD,...,R5GFD,R5GAD,HomeSquad,HomeAge,HomeForeigners,HomeTotalMarketValue,AwaySquad,AwayAge,AwayForeigners,AwayTotalMarketValue
0,2023-2024,2023-08-11,Burnley,0–3,Manchester City,Loss,0,0.653272,-50.666667,31.0,...,-0.4,1.0,34,25.2,26,2.574300e+08,26,26.2,17,1.320000e+09
1,2023-2024,2023-08-12,Arsenal,2–1,Nottingham Forest,Win,2,1.577128,50.000000,-25.0,...,0.2,-0.6,27,25.6,19,1.160000e+09,33,26.6,26,3.872500e+08
2,2023-2024,2023-08-12,Everton,0–1,Fulham,Loss,0,0.877049,-21.000000,4.0,...,-0.2,-0.2,24,27.6,11,3.314000e+08,26,27.6,23,3.463000e+08
3,2023-2024,2023-08-12,Sheffield United,0–1,Crystal Palace,Loss,0,0.912887,3.333333,15.0,...,-1.4,0.0,29,25.8,17,1.220000e+08,28,26.5,13,4.417000e+08
4,2023-2024,2023-08-12,Brighton,4–1,Luton Town,Win,2,1.424290,28.666667,-11.0,...,1.8,1.6,35,24.6,25,5.117500e+08,36,26.9,20,1.156500e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,2013-2014,2014-05-11,Cardiff City,1–2,Chelsea,Loss,0,NaN,0.000000,0.0,...,-1.0,1.8,42,25.4,26,8.790000e+07,49,24.7,40,5.842000e+08
4176,2013-2014,2014-05-11,West Brom,1–2,Stoke City,Loss,0,NaN,0.000000,0.0,...,-0.2,0.6,33,27.2,24,9.080000e+07,33,26.5,23,1.047000e+08
4177,2013-2014,2014-05-11,Tottenham,3–0,Aston Villa,Win,2,NaN,0.000000,0.0,...,1.6,-0.6,41,23.8,22,2.889500e+08,36,24.7,22,1.095000e+08
4178,2013-2014,2014-05-11,Norwich City,0–2,Arsenal,Loss,0,NaN,0.000000,0.0,...,-1.6,1.0,32,26.6,18,8.930000e+07,41,24.5,34,3.857500e+08
4179,2013-2014,2014-05-11,Sunderland,1–3,Swansea City,Loss,0,NaN,0.000000,0.0,...,1.0,-0.4,39,25.6,28,1.220000e+08,36,25.7,28,1.289300e+08

In [27]:
premier_goal_keeping

        Season               Team  Save_Percentage  Clean_Sheet_Percentage
0    2013-2014            Arsenal             72.1                    44.7
1    2013-2014        Aston Villa             64.9                    23.7
2    2013-2014       Cardiff City             66.4                    18.4
3    2013-2014            Chelsea             77.7                    47.4
4    2013-2014     Crystal Palace             71.6                    31.6
..         ...                ...              ...                     ...
215  2023-2024  Nottingham Forest             61.3                    10.5
216  2023-2024   Sheffield United             62.4                     2.6
217  2023-2024          Tottenham             67.7                    18.4
218  2023-2024           West Ham             72.6                    13.2
219  2023-2024             Wolves             71.9                    13.2

[220 rows x 4 columns]

In [28]:
# Assuming 'Season' column exists and contains strings like '2023-2024'
premier_ranking_modified['Last Season'] = premier_ranking_modified['Season'].str.slice(0, 4).astype(int) - 1
premier_ranking_modified['Last Season'] = premier_ranking_modified['Last Season'].astype(str) + "-" + (premier_ranking_modified['Last Season'].astype(int) + 1).astype(str)
premier_ranking_modified

,Season,Date,Home,Score,Away,Game Outcome,Outcome_Label,LSPR,LSGFD,LSGAD,...,R5GAD,HomeSquad,HomeAge,HomeForeigners,HomeTotalMarketValue,AwaySquad,AwayAge,AwayForeigners,AwayTotalMarketValue,Last Season
0,2023-2024,2023-08-11,Burnley,0–3,Manchester City,Loss,0,0.653272,-50.666667,31.0,...,1.0,34,25.2,26,2.574300e+08,26,26.2,17,1.320000e+09,2022-2023
1,2023-2024,2023-08-12,Arsenal,2–1,Nottingham Forest,Win,2,1.577128,50.000000,-25.0,...,-0.6,27,25.6,19,1.160000e+09,33,26.6,26,3.872500e+08,2022-2023
2,2023-2024,2023-08-12,Everton,0–1,Fulham,Loss,0,0.877049,-21.000000,4.0,...,-0.2,24,27.6,11,3.314000e+08,26,27.6,23,3.463000e+08,2022-2023
3,2023-2024,2023-08-12,Sheffield United,0–1,Crystal Palace,Loss,0,0.912887,3.333333,15.0,...,0.0,29,25.8,17,1.220000e+08,28,26.5,13,4.417000e+08,2022-2023
4,2023-2024,2023-08-12,Brighton,4–1,Luton Town,Win,2,1.424290,28.666667,-11.0,...,1.6,35,24.6,25,5.117500e+08,36,26.9,20,1.156500e+08,2022-2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,2013-2014,2014-05-11,Cardiff City,1–2,Chelsea,Loss,0,NaN,0.000000,0.0,...,1.8,42,25.4,26,8.790000e+07,49,24.7,40,5.842000e+08,2012-2013
4176,2013-2014,2014-05-11,West Brom,1–2,Stoke City,Loss,0,NaN,0.000000,0.0,...,0.6,33,27.2,24,9.080000e+07,33,26.5,23,1.047000e+08,2012-2013
4177,2013-2014,2014-05-11,Tottenham,3–0,Aston Villa,Win,2,NaN,0.000000,0.0,...,-0.6,41,23.8,22,2.889500e+08,36,24.7,22,1.095000e+08,2012-2013
4178,2013-2014,2014-05-11,Norwich City,0–2,Arsenal,Loss,0,NaN,0.000000,0.0,...,1.0,32,26.6,18,8.930000e+07,41,24.5,34,3.857500e+08,2012-2013
4179,2013-2014,2014-05-11,Sunderland,1–3,Swansea City,Loss,0,NaN,0.000000,0.0,...,-0.4,39,25.6,28,1.220000e+08,36,25.7,28,1.289300e+08,2012-2013

In [29]:
# Step 1: Create a mapping of seasons to the set of teams that played in each season
teams_by_season = {}

# Get unique seasons from 'Season' and 'Last Season' columns
all_seasons = pd.unique(premier_ranking_modified[['Season', 'Last Season']].values.ravel('K'))

for season in all_seasons:
    # Get matches for the current season
    season_matches = premier_ranking_modified[premier_ranking_modified['Season'] == season]

    # If there are no matches for the season (possible for 'Last Season' that isn't in 'Season'), skip
    if season_matches.empty:
        teams_by_season[season] = set()
        continue

    # Get unique home and away teams
    home_teams = season_matches['Home'].unique()
    away_teams = season_matches['Away'].unique()

    # Combine home and away teams into a set
    teams = set(home_teams).union(set(away_teams))

    # Store the set of teams for the current season
    teams_by_season[season] = teams

# Step 2: Define a function to check if teams were in the last season
def check_team_in_last_season(row):
    home_team = row['Home']
    away_team = row['Away']
    last_season = row['Last Season']

    # Get the set of teams from the last season
    teams_last_season = teams_by_season.get(last_season, set())

    # Check if the home and away teams were in the last season
    home_in_last_season = home_team in teams_last_season
    away_in_last_season = away_team in teams_last_season

    return pd.Series({
        'HomeTeamInLastSeason': home_in_last_season,
        'AwayTeamInLastSeason': away_in_last_season
    })

# Step 3: Apply the function to the DataFrame
premier_ranking_modified[['HomeTeamInLastSeason', 'AwayTeamInLastSeason']] = premier_ranking_modified.apply(
    check_team_in_last_season, axis=1
)

# Now 'premier_match' has two new columns indicating whether home and away teams were in the last season
premier_ranking_modified

,Season,Date,Home,Score,Away,Game Outcome,Outcome_Label,LSPR,LSGFD,LSGAD,...,HomeAge,HomeForeigners,HomeTotalMarketValue,AwaySquad,AwayAge,AwayForeigners,AwayTotalMarketValue,Last Season,HomeTeamInLastSeason,AwayTeamInLastSeason
0,2023-2024,2023-08-11,Burnley,0–3,Manchester City,Loss,0,0.653272,-50.666667,31.0,...,25.2,26,2.574300e+08,26,26.2,17,1.320000e+09,2022-2023,False,True
1,2023-2024,2023-08-12,Arsenal,2–1,Nottingham Forest,Win,2,1.577128,50.000000,-25.0,...,25.6,19,1.160000e+09,33,26.6,26,3.872500e+08,2022-2023,True,True
2,2023-2024,2023-08-12,Everton,0–1,Fulham,Loss,0,0.877049,-21.000000,4.0,...,27.6,11,3.314000e+08,26,27.6,23,3.463000e+08,2022-2023,True,True
3,2023-2024,2023-08-12,Sheffield United,0–1,Crystal Palace,Loss,0,0.912887,3.333333,15.0,...,25.8,17,1.220000e+08,28,26.5,13,4.417000e+08,2022-2023,False,True
4,2023-2024,2023-08-12,Brighton,4–1,Luton Town,Win,2,1.424290,28.666667,-11.0,...,24.6,25,5.117500e+08,36,26.9,20,1.156500e+08,2022-2023,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,2013-2014,2014-05-11,Cardiff City,1–2,Chelsea,Loss,0,NaN,0.000000,0.0,...,25.4,26,8.790000e+07,49,24.7,40,5.842000e+08,2012-2013,False,False
4176,2013-2014,2014-05-11,West Brom,1–2,Stoke City,Loss,0,NaN,0.000000,0.0,...,27.2,24,9.080000e+07,33,26.5,23,1.047000e+08,2012-2013,False,False
4177,2013-2014,2014-05-11,Tottenham,3–0,Aston Villa,Win,2,NaN,0.000000,0.0,...,23.8,22,2.889500e+08,36,24.7,22,1.095000e+08,2012-2013,False,False
4178,2013-2014,2014-05-11,Norwich City,0–2,Arsenal,Loss,0,NaN,0.000000,0.0,...,26.6,18,8.930000e+07,41,24.5,34,3.857500e+08,2012-2013,False,False
4179,2013-2014,2014-05-11,Sunderland,1–3,Swansea City,Loss,0,NaN,0.000000,0.0,...,25.6,28,1.220000e+08,36,25.7,28,1.289300e+08,2012-2013,False,False

In [30]:
# Step 2: Initialize a dictionary to store the average save percentage and clean sheet percentage of promoted teams by season
avg_goalkeeping_stats_promoted_by_season = {}

# Get a sorted list of seasons to maintain chronological order
seasons = sorted(promoted_teams.keys())

# Loop through each season to calculate the average save percentage and clean sheet percentage of promoted teams
for idx, season in enumerate(seasons):
    if idx == 0:
        # For the first season, assign NaN since there is no previous season to reference
        avg_goalkeeping_stats_promoted_by_season[season] = {'Save_Percentage': np.nan, 'Clean_Sheet_Percentage': np.nan}
    else:
        last_season = seasons[idx - 1]
        # Get the promoted teams from the last season
        teams = promoted_teams[last_season]

        # Get goalkeeping data for these teams in the last season (their first season in the Premier League)
        team_stats = premier_goal_keeping[
            (premier_goal_keeping['Season'] == last_season) &
            (premier_goal_keeping['Team'].isin(teams))
        ]

        # Calculate the average save percentage and clean sheet percentage
        avg_save_percentage = team_stats['Save_Percentage'].mean()
        avg_clean_sheet_percentage = team_stats['Clean_Sheet_Percentage'].mean()

        avg_goalkeeping_stats_promoted_by_season[season] = {
            'Save_Percentage': avg_save_percentage,
            'Clean_Sheet_Percentage': avg_clean_sheet_percentage
        }

# Step 3: Add the 'Previous_Season' column, but only if the season is not the first one in the dataset
def previous_season(season):
    start_year, end_year = season.split('-')
    prev_start_year = str(int(start_year) - 1)
    prev_end_year = str(int(end_year) - 1)
    return f"{prev_start_year}-{prev_end_year}"

# Adding a check for the first season in the dataset
premier_ranking_modified['Previous_Season'] = premier_ranking_modified['Season'].apply(
    lambda x: previous_season(x) if x != seasons[0] else np.nan
)

# Step 4: Create a function to get the last season stats or assign average for promoted teams
def get_last_season_goalkeeping_stats(team, last_season, current_season, in_last_season):
    if pd.isna(last_season):
        # If there is no previous season, return NaN
        return {'Save_Percentage': np.nan, 'Clean_Sheet_Percentage': np.nan}
    if in_last_season:
        # Team was in the league last season, retrieve actual stats
        last_season_stats = premier_goal_keeping[
            (premier_goal_keeping['Team'] == team) &
            (premier_goal_keeping['Season'] == last_season)
        ]
        if not last_season_stats.empty:
            return {
                'Save_Percentage': last_season_stats.iloc[0]['Save_Percentage'],
                'Clean_Sheet_Percentage': last_season_stats.iloc[0]['Clean_Sheet_Percentage']
            }
        else:
            return {'Save_Percentage': np.nan, 'Clean_Sheet_Percentage': np.nan}
    else:
        # Team was promoted this season, assign average stats of promoted teams from the previous season
        avg_stats = avg_goalkeeping_stats_promoted_by_season.get(current_season, {'Save_Percentage': np.nan, 'Clean_Sheet_Percentage': np.nan})
        return avg_stats

# Step 5: Apply the function to create new columns for Home and Away teams
def apply_goalkeeping_stats(row, is_home):
    team = row['Home'] if is_home else row['Away']
    last_season = row['Previous_Season']
    current_season = row['Season']
    in_last_season = row['HomeTeamInLastSeason'] if is_home else row['AwayTeamInLastSeason']
    stats = get_last_season_goalkeeping_stats(team, last_season,current_season, in_last_season)
    return stats

# Apply for Home teams
premier_ranking_modified['HomeSavePercentage_LastSeason'] = premier_ranking_modified.apply(
    lambda row: apply_goalkeeping_stats(row, is_home=True)['Save_Percentage'], axis=1
)

premier_ranking_modified['HomeCleanSheetPercentage_LastSeason'] = premier_ranking_modified.apply(
    lambda row: apply_goalkeeping_stats(row, is_home=True)['Clean_Sheet_Percentage'], axis=1
)

# Apply for Away teams
premier_ranking_modified['AwaySavePercentage_LastSeason'] = premier_ranking_modified.apply(
    lambda row: apply_goalkeeping_stats(row, is_home=False)['Save_Percentage'], axis=1
)

premier_ranking_modified['AwayCleanSheetPercentage_LastSeason'] = premier_ranking_modified.apply(
    lambda row: apply_goalkeeping_stats(row, is_home=False)['Clean_Sheet_Percentage'], axis=1
)

In [31]:
avg_goalkeeping_stats_promoted_by_season

{'2014-2015': {'Save_Percentage': nan, 'Clean_Sheet_Percentage': nan},
 '2015-2016': {'Save_Percentage': 67.76666666666667,
  'Clean_Sheet_Percentage': 22.8},
 '2016-2017': {'Save_Percentage': 58.199999999999996,
  'Clean_Sheet_Percentage': 20.166666666666668},
 '2017-2018': {'Save_Percentage': 71.53333333333335,
  'Clean_Sheet_Percentage': 22.8},
 '2018-2019': {'Save_Percentage': 68.63333333333334,
  'Clean_Sheet_Percentage': 25.433333333333334},
 '2019-2020': {'Save_Percentage': 68.16666666666667,
  'Clean_Sheet_Percentage': 21.066666666666666},
 '2020-2021': {'Save_Percentage': 68.26666666666667,
  'Clean_Sheet_Percentage': 21.933333333333334},
 '2021-2022': {'Save_Percentage': 73.66666666666667,
  'Clean_Sheet_Percentage': 23.7},
 '2022-2023': {'Save_Percentage': 66.63333333333333,
  'Clean_Sheet_Percentage': 16.666666666666668},
 '2023-2024': {'Save_Percentage': 70.16666666666667,
  'Clean_Sheet_Percentage': 21.96666666666667}}

In [32]:
premier_ranking_modified

,Season,Date,Home,Score,Away,Game Outcome,Outcome_Label,LSPR,LSGFD,LSGAD,...,AwayForeigners,AwayTotalMarketValue,Last Season,HomeTeamInLastSeason,AwayTeamInLastSeason,Previous_Season,HomeSavePercentage_LastSeason,HomeCleanSheetPercentage_LastSeason,AwaySavePercentage_LastSeason,AwayCleanSheetPercentage_LastSeason
0,2023-2024,2023-08-11,Burnley,0–3,Manchester City,Loss,0,0.653272,-50.666667,31.0,...,17,1.320000e+09,2022-2023,False,True,2022-2023,70.166667,21.966667,67.400000,34.200000
1,2023-2024,2023-08-12,Arsenal,2–1,Nottingham Forest,Win,2,1.577128,50.000000,-25.0,...,26,3.872500e+08,2022-2023,True,True,2022-2023,70.600000,36.800000,65.900000,21.100000
2,2023-2024,2023-08-12,Everton,0–1,Fulham,Loss,0,0.877049,-21.000000,4.0,...,23,3.463000e+08,2022-2023,True,True,2022-2023,71.900000,23.700000,76.500000,23.700000
3,2023-2024,2023-08-12,Sheffield United,0–1,Crystal Palace,Loss,0,0.912887,3.333333,15.0,...,13,4.417000e+08,2022-2023,False,True,2022-2023,70.166667,21.966667,71.900000,23.700000
4,2023-2024,2023-08-12,Brighton,4–1,Luton Town,Win,2,1.424290,28.666667,-11.0,...,20,1.156500e+08,2022-2023,True,False,2022-2023,64.100000,31.600000,70.166667,21.966667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,2013-2014,2014-05-11,Cardiff City,1–2,Chelsea,Loss,0,NaN,0.000000,0.0,...,40,5.842000e+08,2012-2013,False,False,2012-2013,NaN,NaN,NaN,NaN
4176,2013-2014,2014-05-11,West Brom,1–2,Stoke City,Loss,0,NaN,0.000000,0.0,...,23,1.047000e+08,2012-2013,False,False,2012-2013,NaN,NaN,NaN,NaN
4177,2013-2014,2014-05-11,Tottenham,3–0,Aston Villa,Win,2,NaN,0.000000,0.0,...,22,1.095000e+08,2012-2013,False,False,2012-2013,NaN,NaN,NaN,NaN
4178,2013-2014,2014-05-11,Norwich City,0–2,Arsenal,Loss,0,NaN,0.000000,0.0,...,34,3.857500e+08,2012-2013,False,False,2012-2013,NaN,NaN,NaN,NaN
4179,2013-2014,2014-05-11,Sunderland,1–3,Swansea City,Loss,0,NaN,0.000000,0.0,...,28,1.289300e+08,2012-2013,False,False,2012-2013,NaN,NaN,NaN,NaN

In [33]:
# Create a new DataFrame to store the rolling statistics
home_team_stats = []

# Loop through each row in the dataset
for index, row in premier_ranking_modified.iterrows():
    home_team = row['Home']
    away_team = row['Away']
    match_date = row['Date']

    # Filter to get the matches between the home and away team that happened before the current match date
    past_matches = premier_ranking_modified[
        (
            ((premier_ranking_modified['Home'] == home_team) & (premier_ranking_modified['Away'] == away_team)) |
            ((premier_ranking_modified['Home'] == away_team) & (premier_ranking_modified['Away'] == home_team))
        ) &
        (premier_ranking_modified['Date'] < match_date)
    ].sort_values(by='Date', ascending=False)

    # Get the last 3 matches between these teams
    last_three_matches = past_matches.head(3)

    # Calculate "Goals For" and "Goals Against" for the home team
    home_goals_for = 0
    home_goals_against = 0

    for past_match in last_three_matches.itertuples():
        if past_match.Home == home_team:
            # Replace any en dash or similar characters with a hyphen before splitting
            score_parts = past_match.Score.replace('–', '-').replace('—', '-').split('-')
            home_goals_for += int(score_parts[0])
            home_goals_against += int(score_parts[1])
        else:
            # Replace any en dash or similar characters with a hyphen before splitting
            score_parts = past_match.Score.replace('–', '-').replace('—', '-').split('-')
            home_goals_for += int(score_parts[1])
            home_goals_against += int(score_parts[0])

    # Append the calculated goals for and against to the new DataFrame
    home_team_stats.append({
        'Home': home_team,
        'Away': away_team,
        'Date': match_date,
        'Last_Three_Home_Goals_For': home_goals_for,
        'Last_Three_Home_Goals_Against': home_goals_against
    })

# Convert the list of dictionaries to a DataFrame and merge it with the original DataFrame
home_team_stats_df = pd.DataFrame(home_team_stats)
premier_ranking_modified = pd.merge(premier_ranking_modified, home_team_stats_df, on=['Home', 'Away', 'Date'], how='left')

# Display the modified DataFrame
premier_ranking_modified

,Season,Date,Home,Score,Away,Game Outcome,Outcome_Label,LSPR,LSGFD,LSGAD,...,Last Season,HomeTeamInLastSeason,AwayTeamInLastSeason,Previous_Season,HomeSavePercentage_LastSeason,HomeCleanSheetPercentage_LastSeason,AwaySavePercentage_LastSeason,AwayCleanSheetPercentage_LastSeason,Last_Three_Home_Goals_For,Last_Three_Home_Goals_Against
0,2023-2024,2023-08-11,Burnley,0–3,Manchester City,Loss,0,0.653272,-50.666667,31.0,...,2022-2023,False,True,2022-2023,70.166667,21.966667,67.400000,34.200000,0,6
1,2023-2024,2023-08-12,Arsenal,2–1,Nottingham Forest,Win,2,1.577128,50.000000,-25.0,...,2022-2023,True,True,2022-2023,70.600000,36.800000,65.900000,21.100000,5,1
2,2023-2024,2023-08-12,Everton,0–1,Fulham,Loss,0,0.877049,-21.000000,4.0,...,2022-2023,True,True,2022-2023,71.900000,23.700000,76.500000,23.700000,1,5
3,2023-2024,2023-08-12,Sheffield United,0–1,Crystal Palace,Loss,0,0.912887,3.333333,15.0,...,2022-2023,False,True,2022-2023,70.166667,21.966667,71.900000,23.700000,1,4
4,2023-2024,2023-08-12,Brighton,4–1,Luton Town,Win,2,1.424290,28.666667,-11.0,...,2022-2023,True,False,2022-2023,64.100000,31.600000,70.166667,21.966667,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,2013-2014,2014-05-11,Cardiff City,1–2,Chelsea,Loss,0,NaN,0.000000,0.0,...,2012-2013,False,False,2012-2013,NaN,NaN,NaN,NaN,1,4
4176,2013-2014,2014-05-11,West Brom,1–2,Stoke City,Loss,0,NaN,0.000000,0.0,...,2012-2013,False,False,2012-2013,NaN,NaN,NaN,NaN,0,0
4177,2013-2014,2014-05-11,Tottenham,3–0,Aston Villa,Win,2,NaN,0.000000,0.0,...,2012-2013,False,False,2012-2013,NaN,NaN,NaN,NaN,2,0
4178,2013-2014,2014-05-11,Norwich City,0–2,Arsenal,Loss,0,NaN,0.000000,0.0,...,2012-2013,False,False,2012-2013,NaN,NaN,NaN,NaN,1,4
4179,2013-2014,2014-05-11,Sunderland,1–3,Swansea City,Loss,0,NaN,0.000000,0.0,...,2012-2013,False,False,2012-2013,NaN,NaN,NaN,NaN,0,4

In [34]:
# Assuming 'premier_ranking_modified' is already loaded with your dataset
# Step 1: Convert 'Date' to datetime
premier_ranking_modified['Date'] = pd.to_datetime(premier_ranking_modified['Date'])

# Step 2: Create a DataFrame to store points data for each matchup
home_team_points_stats = []

# Loop through each row in the dataset
for index, row in premier_ranking_modified.iterrows():
    home_team = row['Home']
    away_team = row['Away']
    match_date = row['Date']

    # Filter to get all previous matches between the two teams before the current match date
    past_matches = premier_ranking_modified[
        (
            ((premier_ranking_modified['Home'] == home_team) & (premier_ranking_modified['Away'] == away_team)) |
            ((premier_ranking_modified['Home'] == away_team) & (premier_ranking_modified['Away'] == home_team))
        ) &
        (premier_ranking_modified['Date'] < match_date)
    ].sort_values(by='Date', ascending=False)

    # Get the last 3 matches between these teams
    last_three_matches = past_matches.head(3)

    # Calculate the points earned by the home team in those matches
    points_earned = 0
    for past_match in last_three_matches.itertuples():
        # Access the 'Game_Outcome' column using index from the named tuple
        if past_match.Home == home_team and past_match[premier_ranking_modified.columns.get_loc('Game Outcome') + 1] == 'Win':
            points_earned += 3
        elif past_match.Away == home_team and past_match[premier_ranking_modified.columns.get_loc('Game Outcome') + 1] == 'Loss':
            points_earned += 3
        elif past_match[premier_ranking_modified.columns.get_loc('Game Outcome') + 1] == 'Draw':
            points_earned += 1
        # Loss yields 0 points, so no need to add

    # Append the calculated points to the list
    home_team_points_stats.append({
        'Home': home_team,
        'Away': away_team,
        'Date': match_date,
        'Last_Three_Home_Points': points_earned
    })

# Convert the list of dictionaries to a DataFrame and merge it with the original DataFrame
home_team_points_stats_df = pd.DataFrame(home_team_points_stats)
premier_ranking_modified = pd.merge(premier_ranking_modified, home_team_points_stats_df, on=['Home', 'Away', 'Date'], how='left')

In [35]:
premier_ranking_modified

,Season,Date,Home,Score,Away,Game Outcome,Outcome_Label,LSPR,LSGFD,LSGAD,...,HomeTeamInLastSeason,AwayTeamInLastSeason,Previous_Season,HomeSavePercentage_LastSeason,HomeCleanSheetPercentage_LastSeason,AwaySavePercentage_LastSeason,AwayCleanSheetPercentage_LastSeason,Last_Three_Home_Goals_For,Last_Three_Home_Goals_Against,Last_Three_Home_Points
0,2023-2024,2023-08-11,Burnley,0–3,Manchester City,Loss,0,0.653272,-50.666667,31.0,...,False,True,2022-2023,70.166667,21.966667,67.400000,34.200000,0,6,0
1,2023-2024,2023-08-12,Arsenal,2–1,Nottingham Forest,Win,2,1.577128,50.000000,-25.0,...,True,True,2022-2023,70.600000,36.800000,65.900000,21.100000,5,1,3
2,2023-2024,2023-08-12,Everton,0–1,Fulham,Loss,0,0.877049,-21.000000,4.0,...,True,True,2022-2023,71.900000,23.700000,76.500000,23.700000,1,5,1
3,2023-2024,2023-08-12,Sheffield United,0–1,Crystal Palace,Loss,0,0.912887,3.333333,15.0,...,False,True,2022-2023,70.166667,21.966667,71.900000,23.700000,1,4,3
4,2023-2024,2023-08-12,Brighton,4–1,Luton Town,Win,2,1.424290,28.666667,-11.0,...,True,False,2022-2023,64.100000,31.600000,70.166667,21.966667,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4175,2013-2014,2014-05-11,Cardiff City,1–2,Chelsea,Loss,0,NaN,0.000000,0.0,...,False,False,2012-2013,NaN,NaN,NaN,NaN,1,4,0
4176,2013-2014,2014-05-11,West Brom,1–2,Stoke City,Loss,0,NaN,0.000000,0.0,...,False,False,2012-2013,NaN,NaN,NaN,NaN,0,0,1
4177,2013-2014,2014-05-11,Tottenham,3–0,Aston Villa,Win,2,NaN,0.000000,0.0,...,False,False,2012-2013,NaN,NaN,NaN,NaN,2,0,3
4178,2013-2014,2014-05-11,Norwich City,0–2,Arsenal,Loss,0,NaN,0.000000,0.0,...,False,False,2012-2013,NaN,NaN,NaN,NaN,1,4,0
4179,2013-2014,2014-05-11,Sunderland,1–3,Swansea City,Loss,0,NaN,0.000000,0.0,...,False,False,2012-2013,NaN,NaN,NaN,NaN,0,4,0

In [36]:
# Save the DataFrame to an Excel file
#premier_ranking_modified.to_excel('premier_ranking_modified_updated.xlsx', index=False)

# Download the file
#files.download('premier_ranking_modified_updated.xlsx')